# Generated by Django 6.0.3 on 2026-04-13 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=255, null=True)),
                ('file_path', models.FileField(null=True, upload_to='extractions/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict)),
                ('database_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.connection')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_extractions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
