# Generated by Django 6.0.3 on 2026-04-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='database_type',
            field=models.CharField(blank=True, choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB'), ('clickhouse', 'ClickHouse')], default=None, max_length=20, null=True),
        ),
    ]
