# Generated by Django 6.0.3 on 2026-04-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraction',
            old_name='metadata',
            new_name='batch_size',
        ),
        migrations.RenameField(
            model_name='extraction',
            old_name='db_type',
            new_name='connection',
        ),
        migrations.AddField(
            model_name='extraction',
            name='collection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extraction',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extraction',
            name='port',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extraction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
