# Generated by Django 6.0.3 on 2026-04-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0002_rename_metadata_extraction_batch_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='batch_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
