# Generated by Django 6.0.3 on 2026-04-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0002_alter_extraction_database_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraction',
            name='table',
        ),
    ]
