# Generated by Django 6.0.3 on 2026-04-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0003_remove_extraction_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraction',
            name='file_path',
        ),
        migrations.AddField(
            model_name='extraction',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
