# Generated by Django 6.0.3 on 2026-04-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0004_extraction_result_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='database_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extraction',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extraction',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
