# Generated by Django 6.0.3 on 2026-04-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0004_remove_extraction_file_path_extraction_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraction',
            old_name='database_type',
            new_name='db_type',
        ),
    ]
