# Generated by Django 6.0.3 on 2026-04-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0005_extraction_database_name_extraction_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraction',
            old_name='database_name',
            new_name='dbname',
        ),
    ]
