# Generated by Django 6.0.3 on 2026-04-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0006_rename_database_name_extraction_dbname'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extraction',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
