# Generated by Django 6.0.3 on 2026-04-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0008_alter_extraction_result_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='file_data',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='extraction',
            name='mime_type',
            field=models.CharField(default='text/csv', max_length=50),
        ),
    ]
