# Generated by Django 6.0.3 on 2026-04-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0009_extraction_file_data_extraction_mime_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraction',
            name='age',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='email',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='file_data',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='mime_type',
        ),
        migrations.AlterField(
            model_name='extraction',
            name='result_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
