# Generated by Django 6.0.3 on 2026-04-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='repo_link',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='video_link',
        ),
        migrations.AddField(
            model_name='submission',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.connection'),
        ),
        migrations.AddField(
            model_name='submission',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
