# Generated by Django 6.0.3 on 2026-04-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='metadata',
        ),
        migrations.AddField(
            model_name='submission',
            name='batch_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
