# Generated by Django 6.0.3 on 2026-04-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_remove_submission_repo_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='database_type',
        ),
    ]
