# Generated by Django 6.0.3 on 2026-04-15 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_remove_submission_metadata_submission_batch_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='database_name',
            new_name='connection',
        ),
    ]
