# Generated by Django 6.0.3 on 2026-04-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_rename_database_name_submission_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='connection',
            new_name='database_name',
        ),
    ]
