# Generated by Django 6.0.3 on 2026-04-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_submission_database_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='collection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
