# Generated by Django 6.0.3 on 2026-04-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='db_type',
            new_name='database_type',
        ),
    ]
