# Generated by Django 6.0.3 on 2026-04-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
